# Broadcasting

## Broadcasting is a feature provided by numpy library with which we can perform any arithmetic operations on 2 matrices of any unequal ordered

In [1]:
import numpy as np

### case 1

##### this is basic case where operation is carried on 2 matrices of same shape

In [3]:
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

### Case 2

##### in this case consider the shape of matrix 1 as n1,m1 and shape of matrix 2 as n2,m2.
    

here n1 != n2 , but m1 = m2 and n1 transform stretches to req size i.e n2 ( eka row ni 2nd matrix chya sarvya rows var operation hoil )

In [5]:
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a3)
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [6]:
a3 + a4 # [0,1,2] this row is added to all rows of 2nd matrix

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

### Case 3

##### in this case If n1 = 1 and m1 = m2  then opertaion will take place

In [15]:
a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)
print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
a5 + a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

### Case 4

##### in this case if n1=1 but m1!=m2 then there will be error

In [17]:
a7 = np.arange(3).reshape(1,3)
a8 = np.arange(16).reshape(4,4)
print(a7)
print(a8)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [18]:
a7 + a8

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

### Case 5

##### in this case n1 =m2 =1 and m1==n2 operation will take place

In [19]:
a9 = np.arange(3).reshape(1,3)
a10 = np.arange(3).reshape(3,1)
print(a9)
print(a10)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [20]:
a9 + a10

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Case 6

##### in this case n1=m1=1 and n2,m2 = anything then operation will take place 

In [21]:
a11 = np.arange(1).reshape(1,1)
a12 = np.arange(20).reshape(5,4)
print(a11)
print(a12)

[[0]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [22]:
a11 + a12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Case 7

##### in this case n1=m1=x ( x= any number ) and n2,m2 = any number then operation will take place

In [23]:
a13 = np.arange(4)
a14 = np.arange(20).reshape(5,4)
print(a13)
print(a14)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [24]:
a13 + a14

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])