# Importing library

In [1]:
import numpy as np

## creating a n-d array 

In [2]:
arr1 = np.array([1,2,3,4,5])

## printing the n-d array

In [3]:
arr1

array([1, 2, 3, 4, 5])

## checking the data type   

In [4]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3 = np.zeros((2,3))

In [9]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

# In this function we pass tuple which consists of  n* m  matrix .This function creates matrix of n * m consisting all zero elements

In [10]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#  This function creates a identiy matrix of dimension which is passed to a function

In [12]:
arr6 = np.arange(20)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#  This function creates a array of range equal to value passed to function

In [13]:
arr7 = np.arange(5,21)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr8 = np.arange(0,21,2)
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# parameters are similar to for loop

In [17]:
arr9 = np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# This function takes 3 parameters first is starting value,last is end value, and middle is the number of points at equal distance between start and end point

In [18]:
arr10 = arr8.copy()
arr10

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# This function copy the arr which is passed to function