In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(low=1,high=100,size=20).reshape(5,4)

In [3]:
arr1

array([[35, 16, 51, 40],
       [39,  5, 53, 97],
       [39,  9, 61, 82],
       [17, 35, 30, 78],
       [75, 38, 98, 19]])

Normal indexing

In [4]:
arr1 [2][1]  

9

Conditional indexing

In [6]:
arr1>50  #checking elements greater than 50

array([[False, False,  True, False],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [ True, False,  True, False]])

## Indexing using boolean arrays ( filtering )

In [8]:
arr1[arr1>50]  #only those are true will be considered 

array([51, 53, 97, 61, 82, 78, 75, 98])

In [11]:
arr1 [(arr1>50) & (arr1%2!=0)]

array([51, 53, 97, 61, 75])

In [12]:
arr1 [(arr1>50) & (arr1%2!=0)] =0  #all true values will be converted to 0

In [13]:
arr1

array([[35, 16,  0, 40],
       [39,  5,  0,  0],
       [39,  9,  0, 82],
       [17, 35, 30, 78],
       [ 0, 38, 98, 19]])