In [3]:
import numpy as np

In [4]:
arr1 = np.arange(24)

In [5]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Indexing

## Normal accessing of elements with the index passing 

In [28]:
arr1[4]

array([16, 17, 18, 19])

In [33]:
arr1[2,2]

10

# Reshape

## reshape func is used to change the dimensions (shape) of the array
reshape(no.of rows,no. of cols) in which we want to transform our array

In [10]:
arr1 = np.arange(24).reshape(6,4)

In [7]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Slicing

In multi dimension array if we pass i in [i] we will get that i th row insteaded of one element

## for printing rows

In [11]:
arr1[2]

array([ 8,  9, 10, 11])

## for printing columns

In [16]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

## for printing in between values


In [23]:
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [25]:
arr1[4:,2:]

array([[18, 19],
       [22, 23]])

# Iteration

In [26]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


This func will print all the data of array in proper form

In [27]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
