In [1]:
import numpy as np

# Basic operations on numpy array 

In [2]:
arr1 = np.array([1,2,3,4,5,6])

In [3]:
arr2 = np.array([4,5,6,7,8,9])

Substraction of all elements of arr2 from arr1

In [11]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

Addition of all elements of arr2 with arr1

In [5]:
arr1+arr2

array([ 5,  7,  9, 11, 13, 15])

Multiplying each element of arr1 with each element of arr2 (vector multiplication )

In [7]:
arr3 = arr1*arr2

In [8]:
arr3

array([ 4, 10, 18, 28, 40, 54])

Multiplying each element of arr1 with a number (scalar multiplication )

In [9]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

this will give us boolean value whether the values in arr is greater or smaller than the number provided 

In [12]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [13]:
arr1>3

array([False, False, False,  True,  True,  True])

this dot function will convert the matrix in the form n1 * n2 i.e if we have 2 matrices of shape (n1=2 * m1=3) and (n2=3 * m2=2) first it will check whether the value of m1 is equal to n2 or not then it will convert it into n1 * m2

In [14]:
arr4 = np.arange(6).reshape(2,3)
arr5 = np.arange(12,18).reshape(3,2)

In [22]:
arr4

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
arr4.dot(arr5)

array([[ 46,  49],
       [172, 184]])

In [23]:
arr5

array([[12, 13],
       [14, 15],
       [16, 17]])

gives minimum nd maximum values

In [19]:
arr5.max()

17

In [20]:
arr5.min()

12

gives min and max values from each row or from each col 

In [21]:
arr5.min(axis=0) #which row is minimum

array([12, 13])

In [24]:
arr5.min(axis=1) #which col is minimum

array([12, 14, 16])

In [25]:
arr5.max(axis=0)

array([16, 17])

In [26]:
arr5.max(axis=1)

array([13, 15, 17])

calculate the sum of elements 

In [27]:
arr5.sum()

87

In [28]:
arr5.sum(axis=0) #col wise addition

array([42, 45])

In [29]:
arr5.sum(axis=1) #row wise addition

array([25, 29, 33])

In [30]:
arr5.mean() #will calculate mean

14.5

In [31]:
arr5.std()

1.707825127659933

In [32]:
np.sin(arr5)

array([[-0.53657292,  0.42016704],
       [ 0.99060736,  0.65028784],
       [-0.28790332, -0.96139749]])

In [33]:
np.median(arr5)

14.5

<RED>There are 2 different way of calling functions bcoz some functions are member funcs so need object to call it and some are normal functions . Also know as static and non-static functions<RED>

In [34]:
np.exp(arr5)

array([[  162754.791419  ,   442413.39200892],
       [ 1202604.28416478,  3269017.37247211],
       [ 8886110.52050787, 24154952.7535753 ]])