In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [7]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
arr4 = np.linspace(10,20,10)
arr4

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# Shape

## It shows the dimension of array in the form (no. of rows, no. of col)

In [5]:
arr1.shape

(5,)

In [6]:
arr2.shape

(2, 3)

In [8]:
arr3.shape

(2, 2, 2)

for the case arr3 there are 2 lists in a single consisting of 2 rows and columns therefore in .shape we get three parameters 1. no. rows,2. no. of columns and 3. no. of entities 

# nDim 

## Gives the dimension of the array

In [9]:
arr1.ndim

1

In [10]:
arr2.ndim

2

In [11]:
arr3.ndim

3

# Size

## gives no. of elements in n-d array

In [12]:
arr1.size

5

In [13]:
arr2.size

6

In [14]:
arr3.size

8

# Itemsize

## gives the value of space occupied by the element in the array for eg int occupies 4 bits of space, float occupies 8 bits of space 

In [15]:
arr1.itemsize

4

In [18]:
arr4.itemsize

8

# Dtype

## gives the datatype of elements store in array

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr4.dtype

dtype('float64')

# Astype 

## changes the datatype as per the user need

In [21]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [22]:
arr4.astype('int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])