In [1]:
import numpy as np

# Reshape

## Converts the shape of the provided matrix

In [10]:
arr1 = np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Ravel

## this function converts higher dimensional arrays into 1D array

In [5]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
arr1.ndim

2

In [7]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Transpose

## converts rows into columns and columns into rows

In [12]:
arr1.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

# Stacking

## uses to combine two arrays

In [16]:
arr2 = np.arange(20,32).reshape(3,4)

In [17]:
arr2

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [20]:
arr3 = np.arange(50,62).reshape(3,4)

In [21]:
arr3

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61]])

In [23]:
np.hstack((arr2,arr3))  #stacks (joins) array horizontally

array([[20, 21, 22, 23, 50, 51, 52, 53],
       [24, 25, 26, 27, 54, 55, 56, 57],
       [28, 29, 30, 31, 58, 59, 60, 61]])

In [25]:
np.vstack((arr2,arr3))  #stacks (joins) array vertically

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61]])

# Splitting

## it simply splits the array. It takes 2 parameters ( name_of_array, equal number of parts in which we want split)

In [26]:
np.hsplit(arr3,2)  #horizontally split .

[array([[50, 51],
        [54, 55],
        [58, 59]]),
 array([[52, 53],
        [56, 57],
        [60, 61]])]

In [28]:
np.vsplit(arr1,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]